services:
  java-api:
    build:
      context: ./backend-java
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080

  python-worker:
    build:
      context: ./worker-python
    depends_on:
      - java-api
    environment:
      - WORKER_API_URL=http://java-api:8080
      - LOG_LEVEL=INFO
